In [1]:
import pandas as pd
import numpy as np
from scipy import stats 
import seaborn as sns

In [2]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df=df.drop_duplicates()
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
df2=df.copy()
list=['Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Pregnancies']

In [9]:
df_std = df2.copy(deep=True)
for column in list:
    df_std[column] = (df_std[column] - df_std[column].mean()) / df_std[column].std() 
df=df_std
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639530,0.847771,0.149543,0.906679,-0.692439,0.203880,0.468187,1.425067,1
1,-0.844335,-1.122665,-0.160441,0.530556,-0.692439,-0.683976,-0.364823,-0.190548,0
2,1.233077,1.942458,-0.263769,-1.287373,-0.692439,-1.102537,0.604004,-0.105515,1
3,-0.844335,-0.997558,-0.160441,0.154433,0.123221,-0.493721,-0.920163,-1.040871,0
4,-1.141108,0.503727,-1.503707,0.906679,0.765337,1.408828,5.481337,-0.020483,1

In [10]:
x=df["Outcome"]      #train
y=df.drop(["Outcome"],axis=1)
x1=df2["Outcome"]     #test
y1=df2.drop(["Outcome"],axis=1)

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(y,x,test_size=0.15,stratify=x)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(652, 8)
(116, 8)
(652,)
(116,)

In [12]:
df_class_0 = df[df['Outcome'] == 0]
df_class_1 = df[df['Outcome'] == 1]

In [13]:
df_n_class_0 = df2[df2['Outcome'] == 0]
df_n_class_1 = df2[df2['Outcome'] == 1]

In [14]:
df_class_1_over = df_class_1.sample(500, replace=True)
df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

In [15]:
df_n_class_1_over = df_n_class_1.sample(500, replace=True)
df_test_n_over = pd.concat([df_n_class_0, df_n_class_1_over], axis=0)
df_test_n_over.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,1000.000000,1000.000000,1000.00000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,4.069000,125.376000,68.65500,21.37600,91.243000,32.608600,0.478875,34.378000,0.50000
std,3.520033,32.813585,21.25384,16.30529,127.852737,7.659063,0.331731,11.678763,0.50025
min,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.078000,21.000000,0.00000
25%,1.000000,102.000000,62.00000,0.00000,0.000000,28.000000,0.247000,25.000000,0.00000
50%,3.000000,122.000000,72.00000,24.00000,44.500000,32.400000,0.380500,31.000000,0.50000
75%,7.000000,146.000000,80.00000,34.00000,145.000000,37.200000,0.640000,42.000000,1.00000
max,17.000000,199.000000,122.00000,99.00000,846.000000,67.100000,2.420000,81.000000,1.00000

In [16]:
y1=df_test_over['Outcome']
df_test_over=df_test_over.drop(['Outcome'],axis=1)
X1=df_test_over

In [17]:
y1_2=df_test_n_over['Outcome']
df_test_n_over=df_test_n_over.drop(['Outcome'],axis=1)
X1_2=df_test_n_over

In [18]:
from sklearn.model_selection import train_test_split

X1_s_train,X1_s_test ,y1_s_train, y1_s_test = train_test_split(X1,y1,test_size=0.2,random_state=0,shuffle= True,stratify = y1)
print('training data shape is :{}.'.format(X1_s_train.shape))
print('training label shape is :{}.'.format(y1_s_train.shape))
print('testing data shape is :{}.'.format(X1_s_test.shape))
print('testing label shape is :{}.'.format(y1_s_test.shape))

training data shape is :(800, 8).
training label shape is :(800,).
testing data shape is :(200, 8).
testing label shape is :(200,).

In [19]:
from sklearn.model_selection import train_test_split

X1_s_n_train,X1_s_n_test ,y1_s_n_train, y1_s_n_test = train_test_split(X1_2,y1_2,test_size=0.2,random_state=0,shuffle = True,stratify = y1_2)

In [20]:
from tensorflow.keras import Sequential
import tensorflow as tf
from tensorflow.keras.layers import Dense,Dropout
m=Sequential()
m.add(Dense(256,  activation = 'relu' ,input_shape=([8]))) 
m.add(Dense(256,  activation = 'relu'))
m.add(Dense(1,activation = 'sigmoid'))
m.compile(optimizer= 'adam', loss= 'binary_crossentropy',metrics= ['accuracy','Precision','Recall','AUC'])
epochs = 50
m.fit(X1_s_train ,y1_s_train,epochs= epochs,steps_per_epoch=200,validation_data=(X1_s_test ,y1_s_test))

Epoch 1/50
200/200 [==============================] - 2s 4ms/step - loss: 0.5420 - accuracy: 0.7450 - precision: 0.7475 - recall: 0.7400 - auc: 0.8092 - val_loss: 0.4658 - val_accuracy: 0.7850 - val_precision: 0.8353 - val_recall: 0.7100 - val_auc: 0.8764
Epoch 2/50
200/200 [==============================] - 1s 3ms/step - loss: 0.4928 - accuracy: 0.7475 - precision: 0.7487 - recall: 0.7450 - auc: 0.8412 - val_loss: 0.4148 - val_accuracy: 0.8400 - val_precision: 0.8333 - val_recall: 0.8500 - val_auc: 0.8928
Epoch 3/50
200/200 [==============================] - 1s 3ms/step - loss: 0.4699 - accuracy: 0.7725 - precision: 0.7698 - recall: 0.7775 - auc: 0.8584 - val_loss: 0.4016 - val_accuracy: 0.8550 - val_precision: 0.8586 - val_recall: 0.8500 - val_auc: 0.8961
Epoch 4/50
200/200 [==============================] - 0s 2ms/step - loss: 0.4533 - accuracy: 0.7887 - precision: 0.7824 - recall: 0.8000 - auc: 0.8693 - val_loss: 0.3902 - val_accuracy: 0.8500 - val_precision: 0.8646 - val_recall: 0.8300 - val_auc: 0.9069
Epoch 5/50
200/200 [==============================] - 1s 3ms/step - loss: 0.4524 - accuracy: 0.7887 - precision: 0.7852 - recall: 0.7950 - auc: 0.8703 - val_loss: 0.4011 - val_accuracy: 0.8650 - val_precision: 0.8842 - val_recall: 0.8400 - val_auc: 0.9191
Epoch 6/50
200/200 [==============================] - 0s 2ms/step - loss: 0.4355 - accuracy: 0.7975 - precision: 0.7946 - recall: 0.8025 - auc: 0.8790 - val_loss: 0.3858 - val_accuracy: 0.8250 - val_precision: 0.8571 - val_recall: 0.7800 - val_auc: 0.9092
Epoch 7/50
200/200 [==============================] - 0s 2ms/step - loss: 0.4184 - accuracy: 0.8112 - precision: 0.8059 - recall: 0.8200 - auc: 0.8911 - val_loss: 0.3874 - val_accuracy: 0.8500 - val_precision: 0.8070 - val_recall: 0.9200 - val_auc: 0.9092
Epoch 8/50
200/200 [==============================] - 1s 4ms/step - loss: 0.4114 - accuracy: 0.8050 - precision: 0.7961 - recall: 0.8200 - auc: 0.8929 - val_loss: 0.3681 - val_accuracy: 0.8600 - val_precision: 0.8529 - val_recall: 0.8700 - val_auc: 0.9137
Epoch 9/50
200/200 [==============================] - 1s 4ms/step - loss: 0.3944 - accuracy: 0.8313 - precision: 0.8132 - recall: 0.8600 - auc: 0.9030 - val_loss: 0.3655 - val_accuracy: 0.8700 - val_precision: 0.8700 - val_recall: 0.8700 - val_auc: 0.9178
Epoch 10/50
200/200 [==============================] - 1s 3ms/step - loss: 0.3780 - accuracy: 0.8350 - precision: 0.8333 - recall: 0.8375 - auc: 0.9119 - val_loss: 0.3764 - val_accuracy: 0.8750 - val_precision: 0.8440 - val_recall: 0.9200 - val_auc: 0.9045
Epoch 11/50
200/200 [==============================] - 1s 4ms/step - loss: 0.3760 - accuracy: 0.8300 - precision: 0.8220 - recall: 0.8425 - auc: 0.9116 - val_loss: 0.3756 - val_accuracy: 0.8500 - val_precision: 0.8302 - val_recall: 0.8800 - val_auc: 0.9093
Epoch 12/50
200/200 [==============================] - 1s 4ms/step - loss: 0.3449 - accuracy: 0.8550 - precision: 0.8463 - recall: 0.8675 - auc: 0.9290 - val_loss: 0.3761 - val_accuracy: 0.8500 - val_precision: 0.8365 - val_recall: 0.8700 - val_auc: 0.9087
Epoch 13/50
200/200 [==============================] - 0s 2ms/step - loss: 0.3233 - accuracy: 0.8587 - precision: 0.8345 - recall: 0.8950 - auc: 0.9362 - val_loss: 0.3656 - val_accuracy: 0.8700 - val_precision: 0.8776 - val_recall: 0.8600 - val_auc: 0.9146
Epoch 14/50
200/200 [==============================] - 0s 2ms/step - loss: 0.3050 - accuracy: 0.8725 - precision: 0.8688 - recall: 0.8775 - auc: 0.9450 - val_loss: 0.4000 - val_accuracy: 0.8600 - val_precision: 0.8273 - val_recall: 0.9100 - val_auc: 0.9029
Epoch 15/50
200/200 [==============================] - 1s 3ms/step - loss: 0.2933 - accuracy: 0.8775 - precision: 0.8665 - recall: 0.8925 - auc: 0.9485 - val_loss: 0.4055 - val_accuracy: 0.8450 - val_precision: 0.8485 - val_recall: 0.8400 - val_auc: 0.9017
Epoch 16/50
200/200 [==============================] - 1s 4ms/step - loss: 0.2871 - accuracy: 0.8863 - precision: 0.8705 - recall: 0.9075 - auc: 0.9513 - val_loss: 0.4662 - val_accuracy: 0.8350 - val_precision: 0.8764 - val_recall: 0.7800 - val_auc: 0.8965
Epoch 17/50
200/200 [==============================] - 1s 3ms/step - loss: 0.2786 - accuracy: 0.8763 - precision: 0.8680 - recall: 0.8875 - auc: 0.9539 - val_loss: 0.4356 - val_accuracy: 0.8150 - val_precision: 0.8706 - val_recall: 0.7400 - val_auc: 0.9104
Epoch 18/50
200/200 [==============================] - 0s 2ms/step - loss: 0.2530 - accuracy: 0.9000 - precision: 0.8980 - recall: 0.9025 - auc: 0.9628 - val_loss: 0.4477 - val_accuracy: 0.8150 - val_precision: 0.8621 - val_recall: 0.7500 - val_auc: 0.9023
Epoch 19/50
200/200 [==============================] - 0s 2ms/step - loss: 0.2325 - accuracy: 0.9100 - precision: 0.8961 - recall: 0.9275 - auc: 0.9698 - val_loss: 0.4313 - val_accuracy: 0.8150 - val_precision: 0.8182 - val_recall: 0.8100 - val_auc: 0.8941
Epoch 20/50
200/200 [==============================] - 0s 2ms/step - loss: 0.2210 - accuracy: 0.9150 - precision: 0.9049 - recall: 0.9275 - auc: 0.9727 - val_loss: 0.4453 - val_accuracy: 0.8400 - val_precision: 0.8208 - val_recall: 0.8700 - val_auc: 0.8946
Epoch 21/50
200/200 [==============================] - 0s 2ms/step - loss: 0.2007 - accuracy: 0.9150 - precision: 0.9089 - recall: 0.9225 - auc: 0.9786 - val_loss: 0.4616 - val_accuracy: 0.8350 - val_precision: 0.8131 - val_recall: 0.8700 - val_auc: 0.8851
Epoch 22/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1901 - accuracy: 0.9237 - precision: 0.9084 - recall: 0.9425 - auc: 0.9818 - val_loss: 0.4584 - val_accuracy: 0.8400 - val_precision: 0.8542 - val_recall: 0.8200 - val_auc: 0.9061
Epoch 23/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1788 - accuracy: 0.9375 - precision: 0.9289 - recall: 0.9475 - auc: 0.9820 - val_loss: 0.5191 - val_accuracy: 0.8100 - val_precision: 0.8100 - val_recall: 0.8100 - val_auc: 0.8777
Epoch 24/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1753 - accuracy: 0.9312 - precision: 0.9238 - recall: 0.9400 - auc: 0.9831 - val_loss: 0.5436 - val_accuracy: 0.7900 - val_precision: 0.7843 - val_recall: 0.8000 - val_auc: 0.8839
Epoch 25/50
200/200 [==============================] - 1s 4ms/step - loss: 0.1686 - accuracy: 0.9400 - precision: 0.9272 - recall: 0.9550 - auc: 0.9845 - val_loss: 0.6092 - val_accuracy: 0.8000 - val_precision: 0.7778 - val_recall: 0.8400 - val_auc: 0.8664
Epoch 26/50
200/200 [==============================] - 1s 3ms/step - loss: 0.1557 - accuracy: 0.9450 - precision: 0.9300 - recall: 0.9625 - auc: 0.9879 - val_loss: 0.5537 - val_accuracy: 0.8200 - val_precision: 0.8333 - val_recall: 0.8000 - val_auc: 0.8946
Epoch 27/50
200/200 [==============================] - 1s 3ms/step - loss: 0.1494 - accuracy: 0.9525 - precision: 0.9480 - recall: 0.9575 - auc: 0.9877 - val_loss: 0.6204 - val_accuracy: 0.8150 - val_precision: 0.8247 - val_recall: 0.8000 - val_auc: 0.8765
Epoch 28/50
200/200 [==============================] - 1s 3ms/step - loss: 0.1183 - accuracy: 0.9625 - precision: 0.9557 - recall: 0.9700 - auc: 0.9937 - val_loss: 0.6012 - val_accuracy: 0.8100 - val_precision: 0.7925 - val_recall: 0.8400 - val_auc: 0.8882
Epoch 29/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1185 - accuracy: 0.9588 - precision: 0.9487 - recall: 0.9700 - auc: 0.9934 - val_loss: 0.6682 - val_accuracy: 0.8100 - val_precision: 0.7925 - val_recall: 0.8400 - val_auc: 0.8833
Epoch 30/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1203 - accuracy: 0.9513 - precision: 0.9392 - recall: 0.9650 - auc: 0.9935 - val_loss: 0.6510 - val_accuracy: 0.8250 - val_precision: 0.8095 - val_recall: 0.8500 - val_auc: 0.8786
Epoch 31/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0940 - accuracy: 0.9725 - precision: 0.9773 - recall: 0.9675 - auc: 0.9962 - val_loss: 0.6995 - val_accuracy: 0.8050 - val_precision: 0.7850 - val_recall: 0.8400 - val_auc: 0.8682
Epoch 32/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1059 - accuracy: 0.9750 - precision: 0.9703 - recall: 0.9800 - auc: 0.9922 - val_loss: 0.6982 - val_accuracy: 0.8250 - val_precision: 0.8421 - val_recall: 0.8000 - val_auc: 0.8770
Epoch 33/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0943 - accuracy: 0.9688 - precision: 0.9630 - recall: 0.9750 - auc: 0.9962 - val_loss: 0.6609 - val_accuracy: 0.8350 - val_precision: 0.8252 - val_recall: 0.8500 - val_auc: 0.8900
Epoch 34/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0889 - accuracy: 0.9737 - precision: 0.9679 - recall: 0.9800 - auc: 0.9955 - val_loss: 0.7283 - val_accuracy: 0.8200 - val_precision: 0.8200 - val_recall: 0.8200 - val_auc: 0.8815
Epoch 35/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0675 - accuracy: 0.9837 - precision: 0.9825 - recall: 0.9850 - auc: 0.9981 - val_loss: 0.7629 - val_accuracy: 0.7950 - val_precision: 0.8105 - val_recall: 0.7700 - val_auc: 0.8705
Epoch 36/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0603 - accuracy: 0.9837 - precision: 0.9825 - recall: 0.9850 - auc: 0.9991 - val_loss: 0.7677 - val_accuracy: 0.8050 - val_precision: 0.7748 - val_recall: 0.8600 - val_auc: 0.8742
Epoch 37/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0620 - accuracy: 0.9812 - precision: 0.9825 - recall: 0.9800 - auc: 0.9990 - val_loss: 0.7461 - val_accuracy: 0.8050 - val_precision: 0.8020 - val_recall: 0.8100 - val_auc: 0.8748
Epoch 38/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0615 - accuracy: 0.9812 - precision: 0.9777 - recall: 0.9850 - auc: 0.9987 - val_loss: 0.7908 - val_accuracy: 0.8300 - val_precision: 0.8235 - val_recall: 0.8400 - val_auc: 0.8875
Epoch 39/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0477 - accuracy: 0.9937 - precision: 0.9901 - recall: 0.9975 - auc: 0.9991 - val_loss: 0.8780 - val_accuracy: 0.8200 - val_precision: 0.8077 - val_recall: 0.8400 - val_auc: 0.8684
Epoch 40/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0455 - accuracy: 0.9875 - precision: 0.9851 - recall: 0.9900 - auc: 0.9994 - val_loss: 0.9226 - val_accuracy: 0.8100 - val_precision: 0.7925 - val_recall: 0.8400 - val_auc: 0.8669
Epoch 41/50
200/200 [==============================] - 1s 3ms/step - loss: 0.0454 - accuracy: 0.9887 - precision: 0.9900 - recall: 0.9875 - auc: 0.9991 - val_loss: 0.8897 - val_accuracy: 0.8150 - val_precision: 0.8119 - val_recall: 0.8200 - val_auc: 0.8704
Epoch 42/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0354 - accuracy: 0.9912 - precision: 0.9925 - recall: 0.9900 - auc: 0.9997 - val_loss: 0.9486 - val_accuracy: 0.8150 - val_precision: 0.8000 - val_recall: 0.8400 - val_auc: 0.8717
Epoch 43/50
200/200 [==============================] - 1s 3ms/step - loss: 0.0266 - accuracy: 0.9950 - precision: 0.9950 - recall: 0.9950 - auc: 0.9999 - val_loss: 0.9424 - val_accuracy: 0.8000 - val_precision: 0.8061 - val_recall: 0.7900 - val_auc: 0.8714
Epoch 44/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0299 - accuracy: 0.9937 - precision: 0.9925 - recall: 0.9950 - auc: 0.9998 - val_loss: 0.9837 - val_accuracy: 0.8100 - val_precision: 0.8298 - val_recall: 0.7800 - val_auc: 0.8705
Epoch 45/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0271 - accuracy: 0.9912 - precision: 0.9900 - recall: 0.9925 - auc: 0.9999 - val_loss: 0.9751 - val_accuracy: 0.8000 - val_precision: 0.7941 - val_recall: 0.8100 - val_auc: 0.8747
Epoch 46/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0470 - accuracy: 0.9875 - precision: 0.9875 - recall: 0.9875 - auc: 0.9979 - val_loss: 1.0697 - val_accuracy: 0.7750 - val_precision: 0.7570 - val_recall: 0.8100 - val_auc: 0.8530
Epoch 47/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1402 - accuracy: 0.9550 - precision: 0.9505 - recall: 0.9600 - auc: 0.9873 - val_loss: 0.9960 - val_accuracy: 0.8150 - val_precision: 0.7944 - val_recall: 0.8500 - val_auc: 0.8684
Epoch 48/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0489 - accuracy: 0.9837 - precision: 0.9850 - recall: 0.9825 - auc: 0.9993 - val_loss: 1.0300 - val_accuracy: 0.8250 - val_precision: 0.8421 - val_recall: 0.8000 - val_auc: 0.8713
Epoch 49/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0267 - accuracy: 0.9962 - precision: 0.9950 - recall: 0.9975 - auc: 0.9999 - val_loss: 0.9619 - val_accuracy: 0.8050 - val_precision: 0.8020 - val_recall: 0.8100 - val_auc: 0.8857
Epoch 50/50
200/200 [==============================] - 0s 2ms/step - loss: 0.0207 - accuracy: 0.9962 - precision: 0.9950 - recall: 0.9975 - auc: 0.9999 - val_loss: 1.0055 - val_accuracy: 0.8250 - val_precision: 0.8351 - val_recall: 0.8100 - val_auc: 0.8799

In [21]:
c = tf.lite.TFLiteConverter.from_keras_model(m)
tf_lite=c.convert()
with open('sep.tflite', 'wb') as f:
  f.write(tf_lite)

INFO:tensorflow:Assets written to: C:\Users\hp\AppData\Local\Temp\tmp46ibl7tq\assets